"use client";
import "./global.css";
import Sidebar from "./Sidebar";
import Article from "./Article";
import Footer from "./Footer";
import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//export default function RootLayout({ children }) {

function RootLayout({ children }) {
  const [userData, setUserData] = useState(null);

  useEffect(() => {
    fetch("http://localhost:8080/api/users", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include",
    })
      .then((result) => result.json())
      .then((result) => {
        console.log("Received user data:", result.data);
        setUserData(result.data);
      })
      .catch((error) => console.error("Error fetching user data:", error));
  }, []);

  return (
    <html lang="en">
      <head></head>
      <body
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
          backgroundColor: "#FFF",
        }}
      >
        <div
          style={{
            width: "1150px",
            height: "640px",
            backgroundColor: "#316094",
            display: "flex",
            gap: "10px",
          }}
        >
          {/* 사이드 바 */}
          <div
            className="flex-grow-[1] m-[auto] relative"
            style={{ marginLeft: "30px" }}
          >
            <Sidebar data={userData} />
          </div>
          {/* 메인 Article */}
          <div className="flex-grow-[2.5] m-[auto] relative">
            <Article data={userData}>{children}</Article>
          </div>
          {/* 푸터 */}
          <div className="flex-grow-[1]" style={{ marginRight: "20px" }}>
            <Footer data={userData} />
          </div>
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
